name: Run GridLAB-D simulation

on:

  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: slacgismo/gridlabd:latest

    steps:
    - uses: actions/checkout@v2

    - name: Run simulation
      run: |
        chmod +x .github/runner.sh
        bash -c .github/runner.sh
      
    - name: Save results artifact
      uses: actions/upload-artifact@v2
      with:
        name: gridlabd-results
        path: |
          *
          !__pycache__
          !LICENSE
          !README.md
