name: Run GridLAB-D simulation

on:

  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: slacgismo/gridlabd:latest

    steps:
    - uses: actions/checkout@v2

    - name: Simulation
      run: |
        [ -f gridlabd.pre ] && source gridlabd.pre
        [ ! -z "$GLM_TEMPLATE" ] && gridlabd template get $GLM_TEMPLATE
        [ ! -z "$GLM_WEATHER" ] && gridlabd weather get $GLM_WEATHER
        gridlabd --redirect all ${GLM_PRELOAD} gridlabd.glm ${GLM_WEATHER} ${GLM_TIMEZONE:+-D timezone="$GLM_TIMEZONE"} ${GLM_STARTTIME:+-D starttime="$GLM_STARTTIME"} ${GLM_STOPTIME:+-D starttime="$GLM_STOPTIME"} ${GLM_POSTLOAD} ${GLM_TEMPLATE:+-t "$GLM_TEMPLATE"} 
        [ -f gridlabd.post ] && source gridlabd.post 
        tar cfz gridlabd.tar.gz --exclude '{gridlabd.tar.gz,LICENSE,README.md}' $(find . -size 1 -print)
      
    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: gridlabd-results
        path: gridlabd.tar.gz
