name: Run GridLAB-D simulation

on:

  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: slacgismo/gridlabd:latest

    steps:
    - uses: actions/checkout@v2

    - name: Simulation
      run: |
        [ -f gridlabd.pre ] && source gridlabd.pre
        [ ! -z "$GRIDLABD_TEMPLATE" ] && gridlabd get $GRIDLABD_TEMPLATE
        gridlabd --redirect all gridlabd.glm
        [ -f gridlabd.post ] && source gridlabd.post ${GRIDLABD_TEMPLATE:+-t $GRIDLABD_TEMPLATE}
        tar cfz gridlabd.tar.gz --exclude '{gridlabd.tar.gz,LICENSE,README.md}' $(find . -size 1 -print)
      
    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: gridlabd-results
        path: gridlabd.tar.gz
